# Generated by Django 5.2.5 on 2025-08-25 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_alter_genre_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_position",
                    models.FloatField(
                        default=0.0, verbose_name="Последняя позиция (%)"
                    ),
                ),
                (
                    "last_timecode",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Временная метка"
                    ),
                ),
                (
                    "last_page",
                    models.IntegerField(default=0, verbose_name="Последняя страница"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс чтения",
                "verbose_name_plural": "Прогресс чтения",
                "unique_together": {("user", "book")},
            },
        ),
    ]
